name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest coverage
        coverage run --source smote_variants -m pytest tests/*
    
    - name: CodeCov
      uses: codecov/codecov-action@v3
      with:
        #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        #files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: false # optional (default = false)
        verbose: true # optional (default = false)


    #- name: Coverage comment
    #  id: coverage_comment
    #  uses: ewjoachim/python-coverage-comment-action@v2
    #  with:
    #    GITHUB_TOKEN: ${{ github.token }}
    
    #- name: Store Pull Request comment to be posted
    #  uses: actions/upload-artifact@v2
    #  if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
    #  with:
    #    name: python-coverage-comment-action
    #    path: python-coverage-comment-action.txt